---
version: 2
updates:
    - package-ecosystem: "uv"
      directory: "/"
      schedule:
          interval: "daily"
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "daily"
