---
name: Black

"on":
    push:
        paths:
            - "**.py"
            - ".github/workflows/black.yml"
            - "uv.lock"
            - "pyproject.toml"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    UV_MANAGED_PYTHON: "true"
    UV_LOCKED: "true"

jobs:
    black:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10.18", "3.11.13", "3.12.11", "3.13.7"]
        name: black
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Install uv 0.8.14
              uses: astral-sh/setup-uv@v6.6.0
              with:
                  version: 0.8.14
                  python-version: "${{ matrix.python-version }}"
                  enable-cache: true
                  cache-suffix: python-${{ matrix.python-version }}
                  cache-dependency-glob: |
                      **/uv.lock

            - name: Install dependencies
              run: |+
                  uv run python --version
                  uv sync --extra dev
              env:
                  UV_PYTHON: ${{ matrix.python-version }}

            - name: Analyzing the code with black
              run: uv run black --check $(git ls-files '*.py')
              env:
                  UV_PYTHON: ${{ matrix.python-version }}
