---
name: Gitleaks

"on":
    push:
    pull_request:
    workflow_dispatch:
    schedule:
        - cron: "0 4 * * *" # run once a day at 4 AM

permissions:
    contents: read

jobs:
    gitleaks:
        name: gitleaks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5.0.0
              with:
                  fetch-depth: 0

            - uses: gitleaks/gitleaks-action@v2.3.9
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
