---
name: isort

"on":
    push:
        paths:
            - "**.py"
            - ".github/workflows/isort.yml"
            - "poetry.lock"
            - "pyproject.toml"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    isort:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10", "3.11", "3.12", "3.13"]
        name: isort
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Install poetry 2.1.2
              run: pipx install poetry==2.1.2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5.3.0
              with:
                  python-version: "${{ matrix.python-version }}"
                  cache: "poetry"
                  cache-dependency-path: poetry.toml

            - name: Install dependencies
              run: poetry install --with dev

            - name: Analysing the code with isort
              run: poetry run isort --check-only $(git ls-files '*.py')
