---
name: isort

"on":
    push:
        paths:
            - "**.py"
            - ".github/workflows/bandit.yml"
            - "uv.lock"
            - "pyproject.toml"
    pull_request:
        paths:
            - "**.py"
            - ".github/workflows/bandit.yml"
            - "uv.lock"
            - "pyproject.toml"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

env:
    UV_MANAGED_PYTHON: "true"
    UV_LOCKED: "true"

jobs:
    isort:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10.18", "3.11.13", "3.12.11", "3.13.7"]
        name: isort
        steps:
            - name: Checkout
              uses: actions/checkout@v5.0.0

            - name: Install uv 0.9.5
              uses: astral-sh/setup-uv@v7.1.2
              with:
                  version: "0.9.5"
                  python-version: "${{ matrix.python-version }}"
                  enable-cache: true
                  cache-suffix: python-${{ matrix.python-version }}
                  cache-dependency-glob: |
                      **/uv.lock

            - name: Install dependencies
              run: |+
                  uv run python --version
                  uv sync --extra dev
              env:
                  UV_PYTHON: ${{ matrix.python-version }}

            - name: Analyzing the code with isort
              run: uv run isort --check-only $(git ls-files '*.py')
              env:
                  UV_PYTHON: ${{ matrix.python-version }}
