---
name: "Mypy: Static Typing for Python"

"on":
    push:
        paths:
            - "**.py"
            - ".github/workflows/mypy.yml"
            - "uv.lock"
            - "pyproject.toml"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    mypy:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10", "3.11", "3.12", "3.13"]
        name: mypy
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Install uv 0.8.14
              uses: astral-sh/setup-uv@v6.6.0
              with:
                  version: 0.8.14
                  python-version: "${{ matrix.python-version }}"
                  enable-cache: true
                  cache-suffix: python-${{ matrix.python-version }}
                  cache-dependency-glob: |
                      **/uv.lock

            - name: Install dependencies
              run: |+
                  uv run --python ${{ matrix.python-version }} --managed-python python --version
                  uv sync --python ${{ matrix.python-version }} --managed-python --extra dev

            - name: Analyzing the code with mypy
              run: uv run --python ${{ matrix.python-version }} --managed-python mypy $(git ls-files '*.py')
