---
name: Release
"on":
    push:

permissions:
    contents: write
    actions: write

env:
    UV_MANAGED_PYTHON: "true"
    UV_PYTHON: "3.13.7"

jobs:
    release:
        name: release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5.0.0
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - name: Import GPG key
              id: import-gpg
              uses: crazy-max/ghaction-import-gpg@v6.3.0
              with:
                  gpg_private_key: "${{ secrets.GH_BOT_GPG_PRIVATE_KEY }}"
                  passphrase: "${{ secrets.GH_BOT_GPG_PASSPHRASE }}"
                  git_user_signingkey: true
                  git_commit_gpgsign: true
                  trust_level: 5

            - name: Setup pnpm
              uses: pnpm/action-setup@v4.2.0
              with:
                  version: 10.15.1

            - name: Setup Node
              uses: actions/setup-node@v6.0.0
              with:
                  node-version: lts/*
                  cache-dependency-path: .github/files/pnpm-lock.yaml
                  cache: pnpm

            - name: Install uv 0.9.5
              uses: astral-sh/setup-uv@v7.1.2
              with:
                  version: "0.9.5"
                  python-version: "3.13.7"
                  enable-cache: true
                  cache-suffix: python-3.13.7
                  cache-dependency-glob: |
                      **/uv.lock

            - name: Install dependencies
              run: |+
                  uv run python --version
                  uv sync --extra dev --locked

            - name: Install node dependencies
              run: |+
                  pnpm install semantic-release@24.2.9 \
                      @semantic-release/commit-analyzer@13.0.1 \
                      @semantic-release/release-notes-generator@14.1.0 \
                      @semantic-release/changelog@6.0.3 \
                      @semantic-release/exec@7.1.0 \
                      @semantic-release/git@10.0.1 \
                      @semantic-release/github@11.0.6 --save-dev

            - name: Release
              run: |+
                  git config --global user.email "${{ steps.import-gpg.outputs.email }}"
                  git config --global user.name "${{ steps.import-gpg.outputs.name }}"
                  git config --global user.name "${{ steps.import-gpg.outputs.name }}"
                  pnpm dlx semantic-release@24.2.9 --extends ./.github/files/release.config.cjs
              env:
                  PYPI_PROD_API_TOKEN: ${{ secrets.PYPI_PROD_API_TOKEN }}
                  PYPI_TEST_API_TOKEN: ${{ secrets.PYPI_TEST_API_TOKEN }}
                  GITHUB_TOKEN: "${{ secrets.GH_BOT_API_TOKEN }}"
                  GIT_AUTHOR_NAME: "${{ steps.import-gpg.outputs.name }}"
                  GIT_AUTHOR_EMAIL: "${{ steps.import-gpg.outputs.email }}"
                  GIT_COMMITTER_NAME: "${{ steps.import-gpg.outputs.name }}"
                  GIT_COMMITTER_EMAIL: "${{ steps.import-gpg.outputs.email }}"
