---
name: Release
"on":
    push:

jobs:
    release:
        name: release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - name: Import GPG key
              id: import-gpg
              uses: crazy-max/ghaction-import-gpg@v6.2.0
              with:
                  gpg_private_key: "${{ secrets.GH_BOT_GPG_PRIVATE_KEY }}"
                  passphrase: "${{ secrets.GH_BOT_GPG_PASSPHRASE }}"
                  git_user_signingkey: true
                  git_commit_gpgsign: true
                  trust_level: 5

            - name: Setup Node
              uses: actions/setup-node@v4.1.0
              with:
                  node-version: lts/*
                  cache-dependency-path: .github/files/package-lock.json

            - name: Install uv 0.8.14
              uses: astral-sh/setup-uv@v6.6.0
              with:
                  version: "0.8.14"
                  python-version: "3.10"
                  enable-cache: true
                  cache-suffix: python-3.10
                  cache-dependency-glob: |
                      **/uv.lock

            - name: Install dependencies
              run: |+
                  uv run --python 3.10 --managed-python python --version
                  uv sync --python 3.10 --managed-python

            - name: Install node dependencies
              run: |+
                  npm i semantic-release@24.2.0 \
                      @semantic-release/commit-analyzer@13.0.0 \
                      @semantic-release/release-notes-generator@14.0.1 \
                      @semantic-release/changelog@6.0.3 \
                      @semantic-release/exec@6.0.3 \
                      @semantic-release/git@10.0.1 -D

            - name: Release
              run: |+
                  git config --global user.email "${{ steps.import-gpg.outputs.email }}"
                  git config --global user.name "${{ steps.import-gpg.outputs.name }}"
                  git config --global user.name "${{ steps.import-gpg.outputs.name }}"
                  npx semantic-release@24.2.0 --extends ./.github/files/release.config.cjs
              env:
                  PYPI_PROD_API_TOKEN: ${{ secrets.PYPI_PROD_API_TOKEN }}
                  PYPI_TEST_API_TOKEN: ${{ secrets.PYPI_TEST_API_TOKEN }}
                  GITHUB_TOKEN: "${{ secrets.GH_BOT_API_TOKEN }}"
                  GIT_AUTHOR_NAME: "${{ steps.import-gpg.outputs.name }}"
                  GIT_AUTHOR_EMAIL: "${{ steps.import-gpg.outputs.email }}"
                  GIT_COMMITTER_NAME: "${{ steps.import-gpg.outputs.name }}"
                  GIT_COMMITTER_EMAIL: "${{ steps.import-gpg.outputs.email }}"
